version: '3.9'
services:
  socket-service:
    image: "dngoneumont/capstone:socketapi"
    ports:
      - "8080"
    networks:
      - base-net
    restart: on-failure

  django-frontend:
    image: "dngoneumont/capstone:frontend"
    ports:
      - "8000"
    networks:
      - base-net

  printerdb:
    image: mongo:latest
    container_name: printerdb
    ports:
      - "27017"
    networks:
      - base-net

  userSQLDb:
    image: "dngoneumont/capstone:mysql"
    container_name: userSQLDb
    ports:
      - "3306"
    networks:
      - base-net
    restart: on-failure


  file-service:
    image: "dngoneumont/capstone:fileapi"
    ports:
      - "8080"
    networks:
      - base-net
    restart: on-failure

  user-service:
    image: "dngoneumont/capstone:userapi"
    ports:
      - "8080"
    networks:
      - base-net
    restart: on-failure

  eureka:
    image: "dngoneumont/capstone:eureka"
    ports:
      - "8761"
    networks:
      - base-net
    restart: on-failure

  gateway:
    image: "dngoneumont/capstone:gateway"
    ports:
      - "80:80"
    networks:
      - base-net
    restart: on-failure

networks:
  base-net:
    name: capstonenetwork