package dngo.neumont.capstoneeureka;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@EnableEurekaServer
@SpringBootApplication() //Excludes default autogenerated user
//And only allows for JWT authentication from what I can garner.
public class CapstoneEurekaApplication {

    public static void main(String[] args) {
        SpringApplication.run(CapstoneEurekaApplication.class, args);
    }

}
