server:
  port: 80
#  address: ${MSServerIP}
#  ssl:
#    certificate: classpath:certificate.crt
#    certificate-private-key: classpath:private.key
#    trust-certificate: classpath:ca_bundle.crt


spring:
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: file-route
          uri: lb://file-service
          predicates:
            - Path=/file/**
#        - id: rabbit-route
#          uri: lb://rabbit-service
#          predicates:
#            - Path=/rabbit/**
#        Rabbit mq is deprecated for right now until I can figure out a use for it besides the original consumer purpose
#        - id: rabbit-server
#          uri: amqp://rabbitmqcapstone:5672
#          predicates:
#            - Path=/rabbitserver/**
        - id: django-socket-server
          uri: lb://django-socket-server
          predicates:
            - Path=/socket/**
          filters:
            - RewritePath=/socket/(?<segment>.*), /$\{segment}
        - id: django-socket-route
          uri: lb:wss://django-socket-server
          predicates:
            - Path=/socket.io/**
eureka:
  client:
    service-url:
      #replace with environment variable
      defaultZone: http://eureka:8761/eureka


