package dngo.neumont.filerest;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration;

@SpringBootApplication(exclude = {UserDetailsServiceAutoConfiguration.class}) //Excludes default autogenerated user
public class FileRestApplication {

    public static void main(String[] args) {
        SpringApplication.run(FileRestApplication.class, args);
    }

}
